name: Hello World

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-job1:
    runs-on: ubuntu-latest

    steps:
    - name: hello-world
      run: |
        echo "this is a test workflow"
        echo "hello world"
